language: python
git:
  depth: false
  
jobs:
  include:
    - name: "Python 3.8 on Ubuntu"
      python: 3.8
      addons:
        apt:
          packages:
          - g++
          - libeigen3-dev
    - name: "Python 3.5 on Ubuntu"
      python: 3.5
      addons:
        apt:
          packages:
          - g++
          - libeigen3-dev
    - name: "macOS"
      os: osx
      language: shell       
      
script:
- chmod +x .build.sh
- ./.build.sh
