language: cpp
env:
  global:
  - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
  - CXX_FLAGS="-Wall -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow"
matrix:
  include:
  - os: linux
    dist: xenial
    sudo: true
    compiler: g++
    addons:
      apt:
        packages:
        - g++
        - libeigen3-dev
        - python3-pip
        - python3-dev
        - python3-setuptools
        - python3-wheel
        - python3-setuptools-git
script:
- python3 setup.py bdist_wheel
- cd ..
- python3 -m pip install --user ./python
- python3 -c "from dqrobotics import *"
- cd python
- sudo add-apt-repository ppa:deadsnakes/ppa -y
- sudo apt-get update -q
- sudo apt-get install python3.6 python3.6-dev -y
- curl https://bootstrap.pypa.io/get-pip.py | sudo -H python3.6
- python3.6 -m pip install --user setuptools wheel setuptools-git twine
- python3.6 setup.py bdist_wheel
- cd ..
- python3.6 -m pip install --user ./python
- python3.6 -c "from dqrobotics import *"
- cd python
- cd dist
- rename 's/linux/manylinux1/' *
- cd ..
- python3.6 -m twine upload dist/*
