language: cpp

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    - CXX_FLAGS="-Wall -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow"

matrix:
  include:
    - os: linux
      dist: xenial
      env:
       - PYTHONB=/bin/python3.5
       - PYTHONL=/lib/libpython3.5m.so
       - PYTHONI=/include/python3.5m
      sudo: true
      compiler: g++
      addons:
       apt:
         packages: 
           - g++
           - libeigen3-dev
script:
     - mkdir -p build
     - cd build
     - cmake -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DPYTHON_EXECUTABLE=$(python-config --prefix)$(PYTHONB) -DPYTHON_LIBRARY=$(python-config --prefix)$(PYTHONL) -DPYTHON_INCLUDE_DIR=$(python-config --prefix)${PYTHONI} -DCMAKE_BUILD_TYPE=Release .. 
     - make
