language: python
git:
  depth: false
matrix:
  include:
  - os: linux
    dist: xenial
    sudo: true
    compiler: g++
    python:
    - "3.5"
    - "3.8"
    addons:
      apt:
        packages:
        - g++
        - libeigen3-dev
  - os: osx
  - language: shell
script:
- chmod +x .build.sh
- ./.build.sh
