language: cpp

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    - CXX_FLAGS="-Wall -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow"

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: true
      compiler: g++
      addons:
       apt:
         packages: 
           - g++
           - libeigen3-dev
           - python
           - python-dev

script:
     - mkdir -p build
     - cd build
     - cmake -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DPYTHON_EXECUTABLE=$(python-config --prefix)/bin/python3.5 -DPYTHON_LIBRARY=$(python-config --prefix)/lib/libpython3.5m.so -DPYTHON_INCLUDE_DIR=$(python-config --prefix)/include/python3.5m -DCMAKE_BUILD_TYPE=Release .. 
     if dist = xenial
     - make
